name: iOS starter workflow

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,name=iPhone 8' test
      - name: Build App
        run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'generic/plataform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
