# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Cherry Pick and Open Pull Request

on:
  push:
    branches:
      - main

jobs:
  cherry-pick-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Get the last commit hash
        id: last_commit
        run: |
         LAST_COMMIT_HASH=$(git rev-parse HEAD)
         echo "LAST_COMMIT_HASH=${LAST_COMMIT_HASH}" >> $GITHUB_ENV
         
      - name: Switch to develop branch
        run: |
            git fetch
            git checkout develop
          
      - name: Create a new branch for cherry-pick
        run: |
          git checkout -b cherry-pick-branch_${{ env.LAST_COMMIT_HASH }}
          git cherry-pick -x ${{ env.LAST_COMMIT_HASH }}
          git push origin cherry-pick-branch_${{ env.LAST_COMMIT_HASH }}

      - name: Open Pull Request
        run: |
          hub pull-request -b develop -h cherry-pick-branch_${{ env.LAST_COMMIT_HASH }} -m "Open Pull Request from main to develop (cherry-pick)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
